"""Condition-variable metadata for the TP information database."""

# ruff: noqa: E501

from __future__ import annotations

from dataclasses import asdict, dataclass

DATE_ACCESSED = "2026-05-07"

USNO_API = "https://aa.usno.navy.mil/data/api.html"
USNO_RST_DEFS = "https://aa.usno.navy.mil/faq/RST_defs"
NASA_MOON_PHASES = "https://science.nasa.gov/moon/moon-phases/"
NOAA_COOPS_API = "https://api.tidesandcurrents.noaa.gov/api/uat/"
NOAA_SPRING_NEAP = "https://oceanservice.noaa.gov/facts/springtide.html"
NOAA_TIDE_EDU = "https://oceanservice.noaa.gov/education/tutorial_tides/lessons/ups_downs.html"
USGS_IV = "https://waterservices.usgs.gov/docs/instantaneous-values/instantaneous-values-details/"
USGS_STATS = "https://waterservices.usgs.gov/docs/statistics/statistics-details/"
USGS_PARAMETERS = "https://water.usgs.gov/nwc/NWC/water_quality/tables/constituent.html"
NWS_API = "https://www.weather.gov/documentation/services-web-api"
NWS_GRIDPOINTS = "https://weather-gov.github.io/api/gridpoints"
NOAA_SOLAR_CALCULATOR = "https://gml.noaa.gov/grad/solcalc/azel.html"
ADFG_FISH_COUNTS = "https://www.adfg.alaska.gov/sf/FishCounts/"
ADFG_EONR = "https://www.adfg.alaska.gov/sf/EONR/"
ADFG_FISHING_REPORTS = "https://www.adfg.alaska.gov/sf/FishingReports/index.cfm?ADFG=R2.Home"
ADFG_COMMERCIAL_EO = "https://www.adfg.alaska.gov/index.cfm?adfg=cfnews.main"
ALASKA_DEC_KENAI_WQ = "https://dec.alaska.gov/water/water-quality/nonpoint-source-control/waters-in-the-spotlight/kenai-river-water-quality-monitoring-activities/"
KENAI_CITY_DOCK = "https://www.kenai.city/dipnet/page/city-dock"
KENAI_CITY_DIPNET = "https://www.kenai.city/dipnet"
ALASKA_DNR_KRSMA = "https://dnr.alaska.gov/parks/aspunits/kenai/krsma.htm"
USFWS_KENAI_COMMERCIAL = "https://www.fws.gov/commercial-operations-kenai"

REQUESTED_TP_VARIABLE_NAMES = (
    "moon_phase",
    "moon_illumination_percent",
    "days_from_new_moon",
    "days_from_full_moon",
    "moonrise_time",
    "moonset_time",
    "sunrise_time",
    "sunset_time",
    "civil_twilight_start",
    "civil_twilight_end",
    "tide_stage",
    "tide_direction",
    "hours_until_high_tide",
    "hours_since_low_tide",
    "spring_tide_or_neap_tide",
    "tidal_range",
)

KENAI_RIVER_VARIABLE_NAMES = (
    "hours_after_hot_sunny_day",
    "morning_after_clear_cold_night",
    "rainfall_48hr_in_tributary_basins",
    "river_stage_velocity_change",
    "estimated_water_clarity_from_flow_plus_recent_rain",
    "guide_boat_density_proxy",
    "parking_pressure_proxy",
    "bait_shop_sentiment_score",
    "local_facebook_fish_photo_count",
    "fish_cleaning_station_activity",
    "recent_regulation_change_flag",
    "hours_since_emergency_order_update",
    "commercial_opening_nearby_flag",
    "tide_plus_wind_alignment",
    "moon_phase_plus_tide_range_interaction",
    "sun_angle_at_fishing_time",
)


@dataclass(frozen=True)
class ConditionVariable:
    """Metadata row for a condition variable."""

    name: str
    description: str
    data_type: str
    unit: str
    valid_range: str
    default_value: str
    source_url: str
    source_title: str
    source_organization: str
    date_accessed: str
    code_locations: str
    calculation_notes: str
    status: str = "active"
    display_name: str = ""
    category: str = "general"
    kenai_relevance: str = "General condition variable; Kenai River relevance depends on caller context."
    collection_method: str = "See source adapter or caller-provided input."
    calculation_method: str = "See calculation notes."
    proxy_method: str = "none"
    update_frequency: str = "provider-dependent"
    limitations: str = "Application-specific thresholds should be validated before operational use."

    def as_db_row(self) -> dict[str, str]:
        row = asdict(self)
        if not row["display_name"]:
            row["display_name"] = self.name.replace("_", " ").title()
        return row


def variable(
    name: str,
    description: str,
    data_type: str,
    unit: str,
    valid_range: str,
    default_value: str,
    source_url: str,
    source_title: str,
    source_organization: str,
    code_locations: str,
    calculation_notes: str,
    status: str = "active",
    display_name: str = "",
    category: str = "general",
    kenai_relevance: str = "General condition variable; Kenai River relevance depends on caller context.",
    collection_method: str = "See source adapter or caller-provided input.",
    calculation_method: str = "See calculation notes.",
    proxy_method: str = "none",
    update_frequency: str = "provider-dependent",
    limitations: str = "Application-specific thresholds should be validated before operational use.",
) -> ConditionVariable:
    return ConditionVariable(
        name=name,
        description=description,
        data_type=data_type,
        unit=unit,
        valid_range=valid_range,
        default_value=default_value,
        source_url=source_url,
        source_title=source_title,
        source_organization=source_organization,
        date_accessed=DATE_ACCESSED,
        code_locations=code_locations,
        calculation_notes=calculation_notes,
        status=status,
        display_name=display_name,
        category=category,
        kenai_relevance=kenai_relevance,
        collection_method=collection_method,
        calculation_method=calculation_method,
        proxy_method=proxy_method,
        update_frequency=update_frequency,
        limitations=limitations,
    )


CONDITION_VARIABLES: tuple[ConditionVariable, ...] = (
    variable(
        "base_score",
        "Starting deterministic score before environmental, legal, location, and species adjustments.",
        "integer",
        "score points",
        "0-100",
        "72",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:291; src/kenai_engine/scoring.py:116",
        "Internal baseline; legal closure and restriction records can override it before normal scoring.",
    ),
    variable(
        "active_closure",
        "Whether active emergency-order records indicate a closure.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:292; src/kenai_engine/report_builder.py:333; src/kenai_engine/scoring.py:22",
        "Forces score to 0 and legal status to closed.",
    ),
    variable(
        "active_restriction",
        "Whether active emergency-order records indicate a restriction.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:293; src/kenai_engine/report_builder.py:337; src/kenai_engine/scoring.py:51",
        "Caps the computed score at 45 and sets legal status to restricted.",
    ),
    variable(
        "legal_uncertainty",
        "Whether active regulation records need manual review or have unknown status.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:294; src/kenai_engine/report_builder.py:341; src/kenai_engine/scoring.py:76",
        "Lowers confidence and caps condition status as unknown.",
    ),
    variable(
        "confidence",
        "Numeric confidence score used as the base for source-quality adjustments.",
        "float",
        "ratio",
        "0-1",
        "0.35",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:295; src/kenai_engine/scoring.py:218",
        "Adjusted by stale and missing source-health signals.",
    ),
    variable(
        "location",
        "Selected location score key for reach-specific condition weighting.",
        "string",
        "none",
        "upper_kenai,middle_kenai,soldotna,lower_kenai or null",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/models.py:296; src/kenai_engine/scoring.py:35",
        "Chooses the location score blended into the overall deterministic score.",
    ),
    variable(
        "species",
        "Selected species score key for species-specific condition weighting.",
        "string",
        "none",
        "sockeye,chinook,coho,rainbow_trout,dolly_varden or null",
        "None",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:297; src/kenai_engine/scoring.py:36",
        "Chooses the species score blended into the overall deterministic score.",
    ),
    variable(
        "water_temperature_f",
        "Water temperature normalized to Fahrenheit.",
        "float",
        "degrees Fahrenheit",
        "unbounded; scoring bands currently <38, 45-58, 59-62, >62",
        "None",
        USGS_PARAMETERS,
        "National Water Conditions",
        "U.S. Geological Survey",
        "src/kenai_engine/models.py:298; src/kenai_engine/report_builder.py:325; src/kenai_engine/scoring.py:119",
        "Converted from USGS parameter 00010 Celsius values when needed.",
    ),
    variable(
        "flow_percentile",
        "Current discharge percentile for the day of year.",
        "float",
        "percentile",
        "0-100",
        "None",
        USGS_STATS,
        "Statistics Service Details",
        "U.S. Geological Survey",
        "src/kenai_engine/models.py:299; src/kenai_engine/report_builder.py:328; src/kenai_engine/scoring.py:133",
        "Interpolated from USGS daily discharge percentiles.",
    ),
    variable(
        "gage_height_trend_ft_24h",
        "Recent gage-height change used to classify stable or rapidly rising water.",
        "float",
        "feet per 24 hours",
        "unbounded",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/models.py:300; src/kenai_engine/scoring.py:146",
        "Accepted by the scoring model; report builder currently emits a local trend string instead.",
    ),
    variable(
        "recent_rain_inches_24h",
        "Recent or forecast precipitation over the active 24-hour planning window.",
        "float",
        "inches",
        ">=0",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:301; src/kenai_engine/report_builder.py:346; src/kenai_engine/scoring.py:155",
        "Heavy rain applies a clarity and flow caution.",
    ),
    variable(
        "wind_mph",
        "Wind speed used for casting and boating practicality.",
        "float",
        "miles per hour",
        ">=0",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:302; src/kenai_engine/report_builder.py:347; src/kenai_engine/scoring.py:163",
        "Low wind adds a small bonus; high wind applies a penalty.",
    ),
    variable(
        "barometric_pressure_inhg",
        "Barometric pressure input retained for future pressure-derived condition logic.",
        "float",
        "inches of mercury",
        "unbounded",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:303",
        "Defined on ScoreInput but not currently used by scoring.py.",
        "defined_unused",
    ),
    variable(
        "barometric_trend",
        "Pressure trend class for steady or falling weather-pattern effects.",
        "enum",
        "none",
        "rising,steady,falling or null",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:304; src/kenai_engine/scoring.py:171",
        "Steady trend adds a small bonus; falling trend applies a small penalty.",
    ),
    variable(
        "tide_stage",
        "Lower-river tide stage derived from surrounding high and low NOAA predictions.",
        "enum",
        "none",
        "incoming,high,outgoing,low,unknown or null",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/models.py:305; src/kenai_engine/sources/noaa_tides.py:100; src/kenai_engine/scoring.py:202",
        "Already existed; incoming improves lower-river and some species scores, outgoing reduces lower-river score.",
    ),
    variable(
        "fish_count_3day_avg",
        "Three-day average of recent Kenai sockeye count records.",
        "integer",
        "fish",
        ">=0",
        "None",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:306; src/kenai_engine/report_builder.py:326; src/kenai_engine/scoring.py:222",
        "Boosts or reduces sockeye score based on current official count magnitude.",
    ),
    variable(
        "fish_count_trend",
        "Direction of recent fish-count change.",
        "enum",
        "none",
        "rising,steady,falling,unknown",
        "unknown",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/models.py:307; src/kenai_engine/report_builder.py:349; src/kenai_engine/scoring.py:230",
        "Rising trend helps sockeye and coho scores; falling trend reduces sockeye.",
    ),
    variable(
        "flood_alert_active",
        "Whether active NWS alerts include a flood watch or warning.",
        "boolean",
        "none",
        "true,false",
        "False",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:308; src/kenai_engine/report_builder.py:350; src/kenai_engine/scoring.py:175",
        "Applies a safety-oriented penalty and changes recommended user action.",
    ),
    variable(
        "flood_alert_severity",
        "Severity class for active flood alerts.",
        "enum",
        "none",
        "info,watch,warning",
        "info",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:309; src/kenai_engine/report_builder.py:351; src/kenai_engine/scoring.py:176",
        "Warning applies a larger penalty than watch.",
    ),
    variable(
        "source_freshness_hours",
        "Age of each required source-health record.",
        "mapping",
        "hours",
        "source name to hours >=0",
        "{}",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:310; src/kenai_engine/report_builder.py:355; src/kenai_engine/scoring.py:217",
        "Feeds freshness penalties using per-source thresholds.",
    ),
    variable(
        "missing_sources",
        "Required condition sources absent from usable source health.",
        "list",
        "source names",
        "known source ids",
        "[]",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:311; src/kenai_engine/report_builder.py:356; src/kenai_engine/scoring.py:229",
        "Missing required sources reduce confidence and set freshness status to missing.",
    ),
    variable(
        "flow_cfs",
        "Current river discharge.",
        "float",
        "cubic feet per second",
        ">=0",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:43",
        "Accepted by the pure fishing-condition engine for hydrology context.",
    ),
    variable(
        "flow_trend",
        "Recent flow direction.",
        "enum",
        "none",
        "rising,falling,stable,unknown",
        "unknown",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:45; src/kenai_engine/fishing_conditions.py:324",
        "Stable/falling flow helps; rising flow lowers hydrology score.",
    ),
    variable(
        "gauge_height_ft",
        "Current gage height.",
        "float",
        "feet",
        "unbounded",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:46",
        "Captured in hydrology snapshots; trend-derived stage fit can affect access.",
    ),
    variable(
        "water_temp_f",
        "Current water temperature for the pure fishing-condition engine.",
        "float",
        "degrees Fahrenheit",
        "unbounded; scoring bands currently 45-58 and >62",
        "None",
        USGS_PARAMETERS,
        "National Water Conditions",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:47; src/kenai_engine/fishing_conditions.py:340",
        "Adds a favorable salmonid band or warm-water penalty.",
    ),
    variable(
        "water_temp_trend",
        "Recent water-temperature direction.",
        "enum",
        "none",
        "rising,falling,stable,unknown",
        "unknown",
        USGS_PARAMETERS,
        "National Water Conditions",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:48",
        "Defined in the pure engine input but not currently scored.",
        "defined_unused",
    ),
    variable(
        "turbidity_fnu",
        "Measured turbidity.",
        "float",
        "FNU",
        ">=0",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:49; src/kenai_engine/fishing_conditions.py:353",
        "High measured turbidity lowers visibility-sensitive conditions.",
    ),
    variable(
        "tide_phase",
        "Pure-engine tide phase used to score lower-river timing.",
        "enum",
        "none",
        "incoming,outgoing,slack_high,slack_low,unknown",
        "unknown",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:55; src/kenai_engine/fishing_conditions.py:196; src/kenai_engine/fishing_conditions.py:385",
        "Derived from tide_stage; incoming helps, outgoing/slack penalize.",
    ),
    variable(
        "tide_height_ft",
        "Height of the surrounding NOAA tide prediction.",
        "float",
        "feet MLLW",
        "unbounded",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/models.py:176; src/kenai_engine/fishing_conditions.py:56",
        "Stored from NOAA high/low prediction heights.",
    ),
    variable(
        "height_delta_ft",
        "Absolute height difference between surrounding tide predictions.",
        "float",
        "feet",
        ">=0",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:57; src/kenai_engine/fishing_conditions.py:205",
        "Used to derive movement strength.",
    ),
    variable(
        "hours_until_high",
        "Hours until the next high tide in the pure engine.",
        "float",
        "hours",
        ">=0",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:58; src/kenai_engine/fishing_conditions.py:210",
        "Existing related value; requested TP variable is named hours_until_high_tide.",
    ),
    variable(
        "hours_until_low",
        "Hours until the next low tide in the pure engine.",
        "float",
        "hours",
        ">=0",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:59; src/kenai_engine/fishing_conditions.py:215",
        "Existing value paired with the requested hours_since_low_tide addition.",
    ),
    variable(
        "movement_strength",
        "Normalized tide movement strength derived from tide height delta.",
        "float",
        "ratio",
        "0-1",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:61; src/kenai_engine/fishing_conditions.py:221; src/kenai_engine/fishing_conditions.py:415",
        "Adds a small tide score boost when the tide is moving strongly.",
    ),
    variable(
        "access_tide_relevance",
        "How strongly the selected access point depends on lower-river tide timing.",
        "enum",
        "none",
        "none,low,medium,high",
        "high",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/fishing_conditions.py:62; data/config/spatial_catalog.json",
        "Tide score is neutral when access relevance is none.",
    ),
    variable(
        "wind_direction",
        "Wind direction label from weather observations.",
        "string",
        "cardinal/meteorological text",
        "provider-defined",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/models.py:160; src/kenai_engine/fishing_conditions.py:69",
        "Currently reported as context; wind speed drives score.",
    ),
    variable(
        "pressure_trend",
        "Pure-engine pressure trend class.",
        "enum",
        "none",
        "rising,falling,stable,unknown",
        "unknown",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:70; src/kenai_engine/fishing_conditions.py:454",
        "Stable trend helps; falling trend applies a small weather penalty.",
    ),
    variable(
        "precipitation_inches_24h",
        "Pure-engine precipitation amount.",
        "float",
        "inches",
        ">=0",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:71; src/kenai_engine/fishing_conditions.py:449",
        "Heavy rain applies runoff and clarity caution.",
    ),
    variable(
        "cloud_cover_percent",
        "Cloud cover percentage retained for future light/visibility context.",
        "float",
        "percent",
        "0-100",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:72",
        "Defined in pure-engine weather input but not currently scored.",
        "defined_unused",
    ),
    variable(
        "storm_signal",
        "Whether weather data indicates storm conditions.",
        "boolean",
        "none",
        "true,false",
        "False",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:73; src/kenai_engine/fishing_conditions.py:457",
        "Applies a conservative planning penalty.",
    ),
    variable(
        "severe_weather_signal",
        "Whether weather data indicates severe weather.",
        "boolean",
        "none",
        "true,false",
        "False",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:74; src/kenai_engine/fishing_conditions.py:457",
        "Applies a conservative planning penalty.",
    ),
    variable(
        "run_phase",
        "Historical or current run-timing phase.",
        "enum",
        "none",
        "Pre-Peak,Peak,Post-Peak,Unknown",
        "Unknown",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/fishing_conditions.py:78; src/kenai_engine/fishing_conditions.py:479",
        "Peak timing improves seasonal biological score.",
    ),
    variable(
        "run_timing_percentile",
        "Relative run-timing position from seed historical records.",
        "float",
        "ratio",
        "0-1",
        "None",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/fishing_conditions.py:79; data/config/historical_sockeye_run_timing.csv",
        "Loaded for biological context; current scoring uses run_phase and pulse strength.",
    ),
    variable(
        "pulse_strength",
        "Normalized recent run pulse indicator.",
        "float",
        "ratio",
        "-1 to 1",
        "None",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/fishing_conditions.py:81; src/kenai_engine/fishing_conditions.py:512",
        "Large positive pulse improves score; negative pulse reduces score.",
    ),
    variable(
        "seven_day_avg",
        "Seven-day fish-count average used by the pure condition engine.",
        "integer",
        "fish",
        ">=0",
        "None",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/fishing_conditions.py:82; src/kenai_engine/fishing_conditions.py:529",
        "High recent average strengthens the recent activity signal.",
    ),
    variable(
        "historical_only",
        "Whether biological context came only from seed historical data.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_FISH_COUNTS,
        "Fish Counts - Sport Fish",
        "Alaska Department of Fish and Game",
        "src/kenai_engine/fishing_conditions.py:83; src/kenai_engine/fishing_conditions.py:516",
        "Applies a confidence/score caution so historical context is not treated as live data.",
    ),
    variable(
        "access_id",
        "Access-point identifier for local condition fit.",
        "string",
        "none",
        "configured access id or null",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:87; data/config/spatial_catalog.json",
        "Compared with selected access id when scoring access match.",
    ),
    variable(
        "selected_access_id",
        "User-selected access-point identifier.",
        "string",
        "none",
        "configured access id or null",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:88; src/kenai_engine/fishing_conditions.py:550",
        "Determines whether score is local to the selected access or a general fallback.",
    ),
    variable(
        "tide_relevance",
        "Access catalog tide relevance for selected access.",
        "enum",
        "none",
        "none,low,medium,high",
        "none",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "src/kenai_engine/models.py:265; src/kenai_engine/fishing_conditions.py:89; data/config/spatial_catalog.json",
        "Neutralizes tide scoring for non-tide-relevant access.",
    ),
    variable(
        "source_degraded",
        "Whether access/source context is degraded.",
        "boolean",
        "none",
        "true,false",
        "False",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:90; src/kenai_engine/fishing_conditions.py:569",
        "Applies a small access penalty.",
    ),
    variable(
        "match_confidence",
        "Confidence that a condition signal matches the selected access.",
        "float",
        "ratio",
        "0-1",
        "0.5",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:91; src/kenai_engine/fishing_conditions.py:552",
        "Scales the access-match bonus.",
    ),
    variable(
        "stage_fit",
        "Normalized fit between water stage and selected access.",
        "float",
        "ratio",
        "0-1",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/fishing_conditions.py:92; src/kenai_engine/fishing_conditions.py:567",
        "Moves access score up or down around neutral.",
    ),
    variable(
        "data_freshness_status",
        "Freshness label used by the pure fishing-condition engine.",
        "enum",
        "none",
        "fresh,stale,missing,cached,malformed",
        "fresh",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:35; src/kenai_engine/fishing_conditions.py:594",
        "Controls confidence and score-quality multiplier.",
    ),
    variable(
        "data_freshness_age_hours",
        "Age of a source represented in pure-engine freshness metadata.",
        "float",
        "hours",
        ">=0",
        "None",
        NWS_API,
        "API Web Service",
        "National Weather Service",
        "src/kenai_engine/fishing_conditions.py:36; src/kenai_engine/fishing_conditions.py:592",
        "Compared to source freshness limits.",
    ),
    variable(
        "moon_phase",
        "Current lunar phase name.",
        "enum",
        "none",
        "new Moon,waxing crescent,first quarter,waxing gibbous,full Moon,waning gibbous,third quarter,waning crescent",
        "None",
        USNO_API,
        "Astronomical Applications API v4.0.1",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO rstt/oneday returns curphase and closest phase, while NASA documents the eight-phase cycle.",
        "planned",
    ),
    variable(
        "moon_illumination_percent",
        "Percent of the Moon apparent disk illuminated.",
        "float",
        "percent",
        "0-100",
        "None",
        USNO_API,
        "Astronomical Applications API v4.0.1",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO rstt/oneday returns fracillum.",
        "planned",
    ),
    variable(
        "days_from_new_moon",
        "Elapsed days since the nearest previous new Moon.",
        "float",
        "days",
        "0-29.5",
        "None",
        NASA_MOON_PHASES,
        "Moon Phases",
        "NASA Science",
        "not yet read by calculation logic",
        "Requested TP variable derived from primary phase times; NASA documents the roughly 29.5-day phase cycle.",
        "planned",
    ),
    variable(
        "days_from_full_moon",
        "Elapsed days since the nearest previous full Moon.",
        "float",
        "days",
        "0-29.5",
        "None",
        NASA_MOON_PHASES,
        "Moon Phases",
        "NASA Science",
        "not yet read by calculation logic",
        "Requested TP variable derived from primary phase times; NASA documents full Moon geometry and the phase cycle.",
        "planned",
    ),
    variable(
        "moonrise_time",
        "Local time of Moon rise for the target location and date.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below horizon",
        "None",
        USNO_API,
        "Astronomical Applications API v4.0.1",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO rstt/oneday returns Moon rise/set phenomena.",
        "planned",
    ),
    variable(
        "moonset_time",
        "Local time of Moon set for the target location and date.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below horizon",
        "None",
        USNO_API,
        "Astronomical Applications API v4.0.1",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO rstt/oneday returns Moon rise/set phenomena.",
        "planned",
    ),
    variable(
        "sunrise_time",
        "Local time of sunrise.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below horizon",
        "None",
        USNO_RST_DEFS,
        "Rise, Set, and Twilight Definitions",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO defines sunrise/sunset computation by solar zenith distance.",
        "planned",
    ),
    variable(
        "sunset_time",
        "Local time of sunset.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below horizon",
        "None",
        USNO_RST_DEFS,
        "Rise, Set, and Twilight Definitions",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; USNO defines sunrise/sunset computation by solar zenith distance.",
        "planned",
    ),
    variable(
        "civil_twilight_start",
        "Local morning civil twilight begin time.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below twilight limit",
        "None",
        USNO_RST_DEFS,
        "Rise, Set, and Twilight Definitions",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; civil twilight begins when the Sun center is 6 degrees below the horizon.",
        "planned",
    ),
    variable(
        "civil_twilight_end",
        "Local evening civil twilight end time.",
        "datetime",
        "local time",
        "valid datetime or null when continuously above/below twilight limit",
        "None",
        USNO_RST_DEFS,
        "Rise, Set, and Twilight Definitions",
        "U.S. Naval Observatory Astronomical Applications Department",
        "not yet read by calculation logic",
        "Requested TP variable; civil twilight ends when the Sun center is 6 degrees below the horizon.",
        "planned",
    ),
    variable(
        "tide_direction",
        "Direction of tide movement between surrounding high and low predictions.",
        "enum",
        "none",
        "incoming,outgoing,slack,unknown",
        "unknown",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "represented by src/kenai_engine/fishing_conditions.py:55 tide_phase",
        "Requested TP variable; current code represents this as tide_phase/stage rather than this exact name.",
        "planned",
    ),
    variable(
        "hours_until_high_tide",
        "Hours until the next high tide prediction.",
        "float",
        "hours",
        ">=0",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "related existing field src/kenai_engine/fishing_conditions.py:58 hours_until_high",
        "Requested TP variable; exact name added to metadata, while pure engine currently uses hours_until_high.",
        "planned",
    ),
    variable(
        "hours_since_low_tide",
        "Hours elapsed since the previous low tide prediction.",
        "float",
        "hours",
        ">=0",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "not yet read by calculation logic",
        "Requested TP variable derivable from the previous low tide prediction and generated_at.",
        "planned",
    ),
    variable(
        "spring_tide_or_neap_tide",
        "Whether the tide window is closer to spring tide, neap tide, or neither.",
        "enum",
        "none",
        "spring,neap,neither,unknown",
        "unknown",
        NOAA_SPRING_NEAP,
        "What are spring and neap tides?",
        "NOAA National Ocean Service",
        "not yet read by calculation logic",
        "Requested TP variable; source ties spring tides to new/full Moon and neap tides to quarter phases.",
        "planned",
    ),
    variable(
        "tidal_range",
        "Height difference between a paired high and low tide.",
        "float",
        "feet",
        ">=0",
        "None",
        NOAA_TIDE_EDU,
        "Tides and Water Levels: The Ups and Downs of Tides",
        "NOAA National Ocean Service",
        "related existing field src/kenai_engine/fishing_conditions.py:57 height_delta_ft",
        "Requested TP variable; current code stores a related high/low height delta as height_delta_ft.",
        "planned",
    ),
)

KENAI_RIVER_CONDITION_VARIABLES: tuple[ConditionVariable, ...] = (
    variable(
        "hours_after_hot_sunny_day",
        "Hours elapsed since a hot, sunny Kenai-area day ended.",
        "float",
        "hours",
        ">=0",
        "None",
        NWS_GRIDPOINTS,
        "National Weather Service API: gridpoints",
        "National Weather Service",
        "not yet read by calculation logic",
        "Prepared Kenai-specific weather variable. Proposed threshold: daytime max temperature >=70 F and daytime sky cover <=25 percent at the Kenai/Soldotna gridpoint, then count hours since local sunset/end of day.",
        "planned",
        display_name="Hours After Hot Sunny Day",
        category="weather",
        kenai_relevance="Kenai River fishing conditions can change after warm sunny periods that may raise shallow near-bank water temperatures and alter angler/fish timing.",
        collection_method="Use NWS API gridpoint forecast/observations for Kenai or Soldotna; prefer structured JSON instead of page scraping.",
        calculation_method="Evaluate prior local day max temperature and sky cover; if threshold is met, compute hours since the qualifying period ended in Alaska local time.",
        proxy_method="Weather proxy; not a direct biological measurement.",
        update_frequency="Hourly to forecast-cycle dependent from NWS.",
        limitations="Thresholds are local heuristics and are not currently validated against Kenai catch data.",
    ),
    variable(
        "morning_after_clear_cold_night",
        "Flag for a morning following a clear, cold overnight period in the Kenai River area.",
        "boolean",
        "none",
        "true,false",
        "False",
        NWS_GRIDPOINTS,
        "National Weather Service API: gridpoints",
        "National Weather Service",
        "not yet read by calculation logic",
        "Prepared Kenai-specific weather variable. Proposed threshold: overnight minimum temperature <=40 F and overnight sky cover <=25 percent, evaluated before 10:00 Alaska local time.",
        "planned",
        display_name="Morning After Clear Cold Night",
        category="weather",
        kenai_relevance="Kenai River morning bite and access comfort can differ after radiational cooling nights near Soldotna, Cooper Landing, and the lower river.",
        collection_method="Use NWS gridpoint temperature and sky-cover fields for relevant Kenai River access locations.",
        calculation_method="Calculate overnight local min temperature and mean/max sky cover from sunset to sunrise; return true during the following morning window.",
        proxy_method="Weather proxy for overnight cooling and clear-sky radiational conditions.",
        update_frequency="Hourly to forecast-cycle dependent from NWS.",
        limitations="Cold/clear thresholds are operational assumptions and should be tuned against local observations.",
    ),
    variable(
        "rainfall_48hr_in_tributary_basins",
        "Estimated 48-hour precipitation across Kenai River tributary basins.",
        "float",
        "inches",
        ">=0",
        "None",
        NWS_GRIDPOINTS,
        "National Weather Service API: gridpoints",
        "National Weather Service",
        "not yet read by calculation logic",
        "Prepared Kenai-specific hydrology variable. Aggregate NWS quantitative precipitation over representative tributary basin points such as Russian River, Moose River, Funny River, and Cooper Landing/Soldotna context points.",
        "planned",
        display_name="48-Hour Tributary Basin Rainfall",
        category="hydrology",
        kenai_relevance="Tributary rainfall can change Kenai River stage, flow, and clarity differently by river section.",
        collection_method="Use NWS gridpoint quantitativePrecipitation JSON for configured tributary basin points; avoid HTML scraping.",
        calculation_method="Sum precipitation over the latest 48 hours for each configured basin point and optionally weight by basin relevance.",
        proxy_method="Regional precipitation proxy for tributary runoff when basin-specific gauges are unavailable.",
        update_frequency="Hourly to forecast-cycle dependent from NWS.",
        limitations="Point forecasts are not full basin areal precipitation; basin point list must be maintained.",
    ),
    variable(
        "river_stage_velocity_change",
        "Recent change in river stage/discharge used as a velocity or movement proxy.",
        "float",
        "normalized delta",
        "unbounded",
        "None",
        USGS_IV,
        "Instantaneous Values Service",
        "U.S. Geological Survey",
        "src/kenai_engine/sources/usgs.py:260; related existing trend fields",
        "Prepared Kenai-specific hydrology variable using USGS Kenai gauges such as 15258000, 15266010, 15266110, and 15266300. Compute recent stage and discharge deltas over a 24-hour window; use discharge/stage trend as velocity proxy where direct velocity is unavailable.",
        "planned",
        display_name="River Stage Velocity Change",
        category="hydrology",
        kenai_relevance="The Kenai River condition engine already uses Kenai USGS gauges; rapid stage/discharge changes affect access, clarity, and fishability.",
        collection_method="Use USGS instantaneous-values API for configured Kenai River gauges.",
        calculation_method="Compare recent median stage/discharge readings against earlier readings in a fixed window; normalize by local historical or configured thresholds.",
        proxy_method="Stage/discharge trend proxy for velocity when direct velocity is not published for the selected gauge.",
        update_frequency="Near real time; typically 15-60 minute observations depending on station telemetry.",
        limitations="Velocity is inferred, not directly measured; ice, rating changes, or telemetry gaps can distort interpretation.",
    ),
    variable(
        "estimated_water_clarity_from_flow_plus_recent_rain",
        "Estimated water clarity from recent flow/stage changes, rainfall, and turbidity when available.",
        "float",
        "clarity score",
        "0-1",
        "None",
        ALASKA_DEC_KENAI_WQ,
        "Kenai River Water Quality Monitoring Activities",
        "Alaska Department of Environmental Conservation",
        "related existing fields src/kenai_engine/fishing_conditions.py:49; src/kenai_engine/scoring.py:133",
        "Prepared Kenai-specific clarity proxy. Use measured turbidity where available; otherwise reduce clarity estimate as flow percentile, stage rise, and 48-hour tributary rainfall increase.",
        "planned",
        display_name="Estimated Water Clarity From Flow Plus Recent Rain",
        category="hydrology",
        kenai_relevance="Kenai River water quality and turbidity are local concerns; clarity affects visibility-sensitive fishing conditions.",
        collection_method="Combine USGS flow/stage/turbidity when available with NWS precipitation for Kenai tributary basin points.",
        calculation_method="Start from neutral clarity, penalize high flow percentile, rising stage/discharge, and recent rainfall; override or calibrate with measured turbidity.",
        proxy_method="Hydrologic clarity proxy when direct turbidity/visibility data is missing.",
        update_frequency="Hourly to daily depending on available USGS/NWS inputs.",
        limitations="Proxy should be visibly labeled; glacial flour, boat wake, local bank erosion, and tributary pulses may not be captured.",
    ),
    variable(
        "guide_boat_density_proxy",
        "Manual or public-data proxy for guide/boat density near Kenai River access points.",
        "float",
        "index",
        "0-1",
        "None",
        ALASKA_DNR_KRSMA,
        "Kenai River Special Management Area",
        "Alaska Department of Natural Resources",
        "not yet read by calculation logic",
        "Prepared access-pressure proxy. Use official public access/permit context and manually entered observations; do not scrape personal guide identities or private tracking data.",
        "planned",
        display_name="Guide Boat Density Proxy",
        category="access_pressure",
        kenai_relevance="Guide and boat pressure can change practical fishing conditions on the Kenai River, especially lower and middle river boat corridors.",
        collection_method="Manual input or approved official aggregate/public operational data only.",
        calculation_method="Normalize observed/approved aggregate boat or guide activity to a 0-1 pressure index by access point and time window.",
        proxy_method="Manual/aggregate access-pressure proxy.",
        update_frequency="Manual observation cadence or provider-specific.",
        limitations="No reliable live public aggregate source was found; avoid scraping private guide data or personal information.",
    ),
    variable(
        "parking_pressure_proxy",
        "Manual or public operational proxy for parking pressure at Kenai River access points.",
        "float",
        "index",
        "0-1",
        "None",
        KENAI_CITY_DIPNET,
        "City of Kenai Personal Use Fishery",
        "City of Kenai",
        "not yet read by calculation logic",
        "Prepared access-pressure proxy. Use public City of Kenai/DNR access information and manual observations; live parking availability should only be used from approved public feeds.",
        "planned",
        display_name="Parking Pressure Proxy",
        category="access_pressure",
        kenai_relevance="Parking pressure affects practical access at Kenai River mouth, City Dock, dipnet, and popular boat/bank access locations.",
        collection_method="Manual input or approved public operational feed; public pages provide facility context rather than live occupancy.",
        calculation_method="Normalize observed occupancy, queue, or closure status into a 0-1 access-pressure index.",
        proxy_method="Manual/access-facility proxy.",
        update_frequency="Manual observation cadence or provider-specific.",
        limitations="Public sources document facilities but do not provide reliable live parking counts.",
    ),
    variable(
        "bait_shop_sentiment_score",
        "Sentiment score from approved public Kenai River fishing report text.",
        "float",
        "sentiment score",
        "-1 to 1",
        "None",
        ADFG_FISHING_REPORTS,
        "Southcentral Alaska Fishing Reports",
        "Alaska Department of Fish and Game",
        "not yet read by calculation logic",
        "Prepared local-activity proxy. Prefer official ADF&G reports; bait-shop text may be used only when public, reputable, and legally reusable.",
        "planned",
        display_name="Bait Shop Sentiment Score",
        category="local_activity",
        kenai_relevance="Local Kenai River reports can add qualitative context, but should not override official hydrology, tide, weather, or regulation data.",
        collection_method="Manual curation or approved public report scraping with terms reviewed.",
        calculation_method="Score curated public text with a deterministic fishability lexicon; store aggregate sentiment only.",
        proxy_method="Text sentiment proxy; no personal data.",
        update_frequency="Manual/provider report cadence.",
        limitations="Bait-shop-specific automated scraping needs source-by-source permission and quality review.",
    ),
    variable(
        "local_facebook_fish_photo_count",
        "Aggregate count of public Kenai River fish-photo posts from approved sources.",
        "integer",
        "posts",
        ">=0",
        "0",
        "source_needed",
        "source_needed",
        "source_needed",
        "not yet read by calculation logic",
        "Prepared local-activity proxy but not safe to automate without an approved public API/source. Do not scrape private profiles, comments, names, or login-gated Facebook content.",
        "manual_input",
        display_name="Local Facebook Fish Photo Count",
        category="local_activity",
        kenai_relevance="Public fish-photo volume may reflect recent Kenai River activity, but it is privacy-sensitive and biased.",
        collection_method="Manual aggregate input or approved API only.",
        calculation_method="Count only public, Kenai River-relevant fish-photo posts in a time window; store aggregate count with no personal data.",
        proxy_method="Privacy-sensitive social activity proxy.",
        update_frequency="Manual/approved API cadence.",
        limitations="No reliable lawful automated public source is configured; marked source_needed/manual input.",
    ),
    variable(
        "fish_cleaning_station_activity",
        "Manual or official-public proxy for fish cleaning station activity.",
        "float",
        "index",
        "0-1",
        "None",
        KENAI_CITY_DOCK,
        "City Dock",
        "City of Kenai",
        "not yet read by calculation logic",
        "Prepared local-activity proxy. Use public facility context and manual observations; do not scrape private cameras or restricted systems.",
        "planned",
        display_name="Fish Cleaning Station Activity",
        category="local_activity",
        kenai_relevance="Cleaning station activity near Kenai lower-river facilities can indicate harvest/activity pressure during personal-use and sport seasons.",
        collection_method="Manual observation or approved official aggregate feed only.",
        calculation_method="Normalize observed station use, queue, or operating status to a 0-1 activity index.",
        proxy_method="Manual public-facility activity proxy.",
        update_frequency="Manual observation cadence or provider-specific.",
        limitations="No reliable live public activity feed is configured; avoid restricted cameras and personal data.",
    ),
    variable(
        "recent_regulation_change_flag",
        "Flag indicating a recent relevant Kenai River regulation or emergency-order change.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "related existing fields src/kenai_engine/models.py:292; src/kenai_engine/report_builder.py:333",
        "Prepared regulation variable. True when a relevant Kenai River ADF&G regulation or emergency order changed within a configured recent window such as 72 hours.",
        "planned",
        display_name="Recent Regulation Change Flag",
        category="regulation",
        kenai_relevance="Kenai River fishing opportunity can change rapidly through ADF&G emergency orders.",
        collection_method="Use ADF&G emergency-order and regulation public pages; parser already handles public emergency-order records.",
        calculation_method="Filter relevant Kenai River orders by species/area and compare published/effective timestamps to generated_at.",
        proxy_method="none",
        update_frequency="Daily or more frequent during active seasons.",
        limitations="PDF-only or ambiguous orders may require manual review.",
    ),
    variable(
        "hours_since_emergency_order_update",
        "Hours since the most recent relevant Kenai River ADF&G emergency-order update.",
        "float",
        "hours",
        ">=0",
        "None",
        ADFG_EONR,
        "Emergency Orders and Press Releases - Sport Fish",
        "Alaska Department of Fish and Game",
        "related existing emergency-order parser and regulation models",
        "Prepared regulation freshness variable. Calculate elapsed hours from the latest relevant Kenai River emergency-order publication or update timestamp.",
        "planned",
        display_name="Hours Since Emergency Order Update",
        category="regulation",
        kenai_relevance="Recency of official Kenai River emergency orders affects legal-confidence messaging.",
        collection_method="Use ADF&G public emergency-order pages and normalized regulation records.",
        calculation_method="generated_at minus latest relevant order publication/update timestamp.",
        proxy_method="none",
        update_frequency="Daily or more frequent during active seasons.",
        limitations="Some ADF&G records may expose effective dates more clearly than page update timestamps.",
    ),
    variable(
        "commercial_opening_nearby_flag",
        "Flag for nearby commercial fishing openings that may affect Kenai River planning context.",
        "boolean",
        "none",
        "true,false",
        "False",
        ADFG_COMMERCIAL_EO,
        "Commercial Fisheries News Releases and Emergency Orders",
        "Alaska Department of Fish and Game",
        "not yet read by calculation logic",
        "Prepared regional regulation/activity variable. Track official Upper Cook Inlet or nearby commercial fishery announcements relevant to Kenai River salmon timing context.",
        "planned",
        display_name="Commercial Opening Nearby Flag",
        category="regulation",
        kenai_relevance="Nearby Upper Cook Inlet commercial openings are Kenai-region context, but they are not direct sport-fishing condition measurements.",
        collection_method="Use ADF&G commercial fishing public announcements/emergency orders.",
        calculation_method="Return true when a configured nearby commercial management area has an active opening within a configured time/distance window.",
        proxy_method="Regional fishery activity proxy.",
        update_frequency="Daily or more frequent during active commercial seasons.",
        limitations="Requires explicit area mapping before affecting condition score.",
    ),
    variable(
        "tide_plus_wind_alignment",
        "Alignment between lower-Kenai tide direction and wind direction/speed.",
        "float",
        "alignment score",
        "-1 to 1",
        "None",
        NOAA_COOPS_API,
        "CO-OPS Data Retrieval API",
        "NOAA Center for Operational Oceanographic Products and Services",
        "related existing fields tide_stage and wind_mph/wind_direction",
        "Prepared lower-river variable. Compare incoming/outgoing tide direction from NOAA predictions with NWS wind direction/speed near the Kenai River mouth.",
        "planned",
        display_name="Tide Plus Wind Alignment",
        category="tide_weather",
        kenai_relevance="At the Kenai River mouth and lower tidewater, tide timing and wind can combine to affect boating/casting practicality.",
        collection_method="Use NOAA CO-OPS tide predictions and NWS wind forecast/observation JSON for Kenai mouth/lower river.",
        calculation_method="Map tide direction to approximate along-channel direction, compare to wind direction using cosine alignment, weight by wind speed.",
        proxy_method="Physical alignment proxy; not a direct hazard model.",
        update_frequency="Hourly to tide-prediction/forecast-cycle dependent.",
        limitations="Local river geometry, waves, and boat handling are not fully represented.",
    ),
    variable(
        "moon_phase_plus_tide_range_interaction",
        "Interaction between lunar phase and lower-Kenai tide range.",
        "float",
        "interaction score",
        "0-1",
        "None",
        NOAA_SPRING_NEAP,
        "What are spring and neap tides?",
        "NOAA National Ocean Service",
        "related existing moon/tide metadata variables",
        "Prepared tide/astronomy variable. Combine moon phase class with NOAA tide range; spring-tide periods near new/full Moon and larger tide ranges score higher.",
        "planned",
        display_name="Moon Phase Plus Tide Range Interaction",
        category="tide_astronomy",
        kenai_relevance="Lower Kenai tidewater timing depends on Cook Inlet tides; lunar phase helps interpret spring/neap tide context.",
        collection_method="Use USNO/NASA moon phase data and NOAA CO-OPS tide predictions for the configured lower-river tide station.",
        calculation_method="Normalize tide range, add phase weight for new/full versus quarter phases, and clamp to 0-1.",
        proxy_method="Astronomy/tide interaction proxy.",
        update_frequency="Daily for moon phase; tide-cycle dependent for tide range.",
        limitations="Should not be treated as a catch predictor without validation.",
    ),
    variable(
        "sun_angle_at_fishing_time",
        "Solar elevation angle for the fishing time and Kenai River access location.",
        "float",
        "degrees",
        "-90 to 90",
        "None",
        NOAA_SOLAR_CALCULATOR,
        "Solar Position Calculator",
        "NOAA Global Monitoring Laboratory",
        "not yet read by calculation logic",
        "Prepared astronomy/light variable. Compute solar elevation from date, time, latitude, and longitude for the selected Kenai River access point.",
        "planned",
        display_name="Sun Angle At Fishing Time",
        category="astronomy",
        kenai_relevance="Kenai River visibility, shade, glare, and timing differ by sun angle across access points and season.",
        collection_method="Calculate locally from selected access lat/lon and time using a documented solar-position algorithm/library.",
        calculation_method="Use NOAA-supported solar-position equations or a vetted library to compute solar elevation/azimuth; store elevation as sun_angle_at_fishing_time.",
        proxy_method="Astronomical light-angle calculation.",
        update_frequency="Per requested fishing time.",
        limitations="Clouds, bank shade, water color, and canyon/terrain shading are separate factors.",
    ),
)

CONDITION_VARIABLES = (*CONDITION_VARIABLES, *KENAI_RIVER_CONDITION_VARIABLES)

CONDITION_VARIABLE_ROWS = tuple(variable.as_db_row() for variable in CONDITION_VARIABLES)
