"""Build app-facing condition reports."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from kenai_engine.models import (
    Alert,
    FishCount,
    LocationCondition,
    Regulation,
    Report,
    ScoreInput,
    SourceHealth,
    UsgsObservation,
)
from kenai_engine.scoring import score_conditions


def build_placeholder_report(
    now: datetime | None = None,
    usgs_observations: list[UsgsObservation] | None = None,
    regulations: list[Regulation] | None = None,
    fish_counts: list[FishCount] | None = None,
    alerts: list[Alert] | None = None,
) -> Report:
    """Build a valid placeholder report until production adapters are implemented."""

    generated_at = now or datetime.now(UTC)
    today = generated_at.date()
    observations = usgs_observations or []
    active_regulations = regulations or [
        Regulation(
            title="MVP placeholder regulation status",
            status="open",
            effective_date=today,
            source_url="https://www.adfg.alaska.gov/",
            summary="No production emergency-order fetch has run in this skeleton.",
        )
    ]
    active_fish_counts = fish_counts or [
        FishCount(
            species="Sockeye salmon",
            location="Kenai River",
            count=0,
            observation_date=today,
            source_url="https://www.adfg.alaska.gov/",
        )
    ]
    active_alerts = alerts or [
        Alert(
            title="Placeholder data",
            severity="info",
            summary="This report is generated by the runnable skeleton.",
            source="kenai-condition-engine",
        )
    ]
    score = score_conditions(_score_input_from_regulations(active_regulations))
    location_notes = score.reasons
    if observations:
        location_notes = [_format_usgs_note(observation) for observation in observations[:3]]

    return Report(
        report_date=today,
        generated_at=generated_at,
        river="Kenai River",
        overall_score=score.overall_score,
        overall_status=score.overall_status,
        confidence=score.confidence,
        summary=_build_summary(score.overall_status, observations, active_alerts),
        locations=[
            LocationCondition(
                name="Kenai River",
                status=score.overall_status,
                score=score.overall_score,
                notes=location_notes,
            )
        ],
        regulations=active_regulations,
        fish_counts=active_fish_counts,
        alerts=active_alerts,
        source_health=[
            _source_health(
                "usgs",
                len(observations),
                "normalized USGS observations",
                generated_at,
            ),
            _source_health(
                "adfg_emergency_orders",
                len(regulations or []),
                "normalized ADFG emergency orders",
                generated_at,
            ),
            _source_health(
                "adfg_fish_counts",
                len(fish_counts or []),
                "normalized ADFG fish count records",
                generated_at,
            ),
            _source_health("nws", len(alerts or []), "normalized NWS alerts", generated_at),
        ],
    )


def write_latest_report(output_dir: Path, report: Report | None = None) -> Path:
    """Write `latest.json` and return its path."""

    output_dir.mkdir(parents=True, exist_ok=True)
    latest_path = output_dir / "latest.json"
    report_to_write = report or build_placeholder_report()
    latest_path.write_text(
        json.dumps(report_to_write.model_dump(mode="json"), indent=2) + "\n",
        encoding="utf-8",
    )
    return latest_path


def load_report(path: Path) -> Report:
    """Load and validate a report JSON file."""

    return Report.model_validate_json(path.read_text(encoding="utf-8"))


def _score_input_from_regulations(regulations: list[Regulation]) -> ScoreInput:
    return ScoreInput(
        active_closure=any(regulation.status == "closed" for regulation in regulations),
        active_restriction=any(regulation.status == "restricted" for regulation in regulations),
    )


def _format_usgs_note(observation: UsgsObservation) -> str:
    return (
        f"USGS {observation.parameter_code} at {observation.site_name}: "
        f"{observation.value:g} {observation.unit}"
    )


def _build_summary(
    status: str,
    usgs_observations: list[UsgsObservation],
    alerts: list[Alert],
) -> str:
    real_alerts = [alert for alert in alerts if alert.source != "kenai-condition-engine"]
    if status == "closed":
        return "Active emergency order indicates a closure. Check official ADFG sources."
    if status == "restricted":
        return "Active emergency order indicates restrictions. Check official ADFG sources."
    if usgs_observations and real_alerts:
        return "MVP report with normalized USGS readings and source alerts."
    if usgs_observations:
        return "MVP report with normalized USGS readings."
    if real_alerts:
        return "MVP report with source alerts."
    return "Placeholder MVP report. Production source fetching is not implemented yet."


def _source_health(
    source: str,
    record_count: int,
    label: str,
    generated_at: datetime,
) -> SourceHealth:
    return SourceHealth(
        source=source,
        status="ok" if record_count else "placeholder",
        last_checked_at=generated_at,
        message=(
            f"{record_count} {label} available."
            if record_count
            else f"Adapter available; no {label} are available yet."
        ),
    )
