"""Build app-facing condition reports."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from kenai_engine.models import (
    Alert,
    FishCount,
    LocationCondition,
    Regulation,
    Report,
    ScoreInput,
    SourceHealth,
    UsgsObservation,
)
from kenai_engine.scoring import score_conditions


def build_placeholder_report(
    now: datetime | None = None,
    usgs_observations: list[UsgsObservation] | None = None,
) -> Report:
    """Build a valid placeholder report until production adapters are implemented."""

    generated_at = now or datetime.now(UTC)
    today = generated_at.date()
    observations = usgs_observations or []
    regulations = [
        Regulation(
            title="MVP placeholder regulation status",
            status="open",
            effective_date=today,
            source_url="https://www.adfg.alaska.gov/",
            summary="No production emergency-order fetch has run in this skeleton.",
        )
    ]
    score = score_conditions(_score_input_from_regulations(regulations))
    location_notes = score.reasons
    if observations:
        location_notes = [_format_usgs_note(observation) for observation in observations[:3]]
    usgs_health = SourceHealth(
        source="usgs",
        status="ok" if observations else "placeholder",
        last_checked_at=generated_at,
        message=(
            f"{len(observations)} normalized USGS observations available."
            if observations
            else "Adapter available; no normalized USGS observations are available yet."
        ),
    )

    return Report(
        report_date=today,
        generated_at=generated_at,
        river="Kenai River",
        overall_score=score.overall_score,
        overall_status=score.overall_status,
        confidence=score.confidence,
        summary="Placeholder MVP report. Production source fetching is not implemented yet.",
        locations=[
            LocationCondition(
                name="Kenai River",
                status=score.overall_status,
                score=score.overall_score,
                notes=location_notes,
            )
        ],
        regulations=regulations,
        fish_counts=[
            FishCount(
                species="Sockeye salmon",
                location="Kenai River",
                count=0,
                observation_date=today,
                source_url="https://www.adfg.alaska.gov/",
            )
        ],
        alerts=[
            Alert(
                title="Placeholder data",
                severity="info",
                summary="This report is generated by the runnable skeleton.",
                source="kenai-condition-engine",
            )
        ],
        source_health=[
            usgs_health,
            SourceHealth(
                source="adfg_emergency_orders",
                status="placeholder",
                last_checked_at=generated_at,
                message="Parser stub available; production fetch not implemented.",
            ),
            SourceHealth(
                source="adfg_fish_counts",
                status="placeholder",
                last_checked_at=generated_at,
                message="Adapter stub available; production fetch not implemented.",
            ),
            SourceHealth(
                source="nws",
                status="placeholder",
                last_checked_at=generated_at,
                message="Adapter stub available; production fetch not implemented.",
            ),
        ],
    )


def write_latest_report(output_dir: Path, report: Report | None = None) -> Path:
    """Write `latest.json` and return its path."""

    output_dir.mkdir(parents=True, exist_ok=True)
    latest_path = output_dir / "latest.json"
    report_to_write = report or build_placeholder_report()
    latest_path.write_text(
        json.dumps(report_to_write.model_dump(mode="json"), indent=2) + "\n",
        encoding="utf-8",
    )
    return latest_path


def load_report(path: Path) -> Report:
    """Load and validate a report JSON file."""

    return Report.model_validate_json(path.read_text(encoding="utf-8"))


def _score_input_from_regulations(regulations: list[Regulation]) -> ScoreInput:
    return ScoreInput(
        active_closure=any(regulation.status == "closed" for regulation in regulations),
        active_restriction=any(regulation.status == "restricted" for regulation in regulations),
    )


def _format_usgs_note(observation: UsgsObservation) -> str:
    return (
        f"USGS {observation.parameter_code} at {observation.site_name}: "
        f"{observation.value:g} {observation.unit}"
    )
